version: '3.8'

services:
  frontend:
    build: ./my-app
    container_name: my-frontend-p2
    ports:
      - '3100:3000'  # Changed port to avoid conflict with Part 1
    volumes:
      - ./my-app:/app  # Code volume
    depends_on:
      - backend

  backend:
    build: ./server
    container_name: my-backend-p2
    ports:
      - '5100:5000'  # Changed port to avoid conflict
    environment:
      - CONNECTION_URL=mongodb+srv://maryamtahir061:meenuu123@clusterweb.l6zg4.mongodb.net/
      - PORT=5000
    volumes:
      - ./server:/app  # Code volume
